# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-InvertedIndex-DB-Pg
version:      0.02
version_from: lib/Search/InvertedIndex/DB/Pg.pm
installdirs:  site
requires:
    Carp:                          0
    DBD::Pg:                       0
    DBI:                           0
    Search::InvertedIndex:         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
